const data = {
	id: "72611040",
	nodeId: "MDQ6VXNlcjcyNjExMDQw",
	displayName: "Emre",
	username: "IEmreOzkayaI",
	profileUrl: "https://github.com/IEmreOzkayaI",
	photos: [{value: "https://avatars.githubusercontent.com/u/72611040?v=4"}],
	provider: "github",
	_raw: '{"login":"IEmreOzkayaI","id":72611040,"node_id":"MDQ6VXNlcjcyNjExMDQw","avatar_url":"https://avatars.githubusercontent.com/u/72611040?v=4","gravatar_id":"","url":"https://api.github.com/users/IEmreOzkayaI","html_url":"https://github.com/IEmreOzkayaI","followers_url":"https://api.github.com/users/IEmreOzkayaI/followers","following_url":"https://api.github.com/users/IEmreOzkayaI/following{/other_user}","gists_url":"https://api.github.com/users/IEmreOzkayaI/gists{/gist_id}","starred_url":"https://api.github.com/users/IEmreOzkayaI/starred{/owner}{/repo}","subscriptions_url":"https://api.github.com/users/IEmreOzkayaI/subscriptions","organizations_url":"https://api.github.com/users/IEmreOzkayaI/orgs","repos_url":"https://api.github.com/users/IEmreOzkayaI/repos","events_url":"https://api.github.com/users/IEmreOzkayaI/events{/privacy}","received_events_url":"https://api.github.com/users/IEmreOzkayaI/received_events","type":"User","site_admin":false,"name":"Emre","company":null,"blog":"ozkayaemre.com","location":null,"email":null,"hireable":null,"bio":null,"twitter_username":null,"public_repos":41,"public_gists":0,"followers":8,"following":7,"created_at":"2020-10-09T12:40:22Z","updated_at":"2023-12-09T16:15:59Z"}',
	_json: {
		login: "IEmreOzkayaI",
		id: 72611040,
		node_id: "MDQ6VXNlcjcyNjExMDQw",
		avatar_url: "https://avatars.githubusercontent.com/u/72611040?v=4",
		gravatar_id: "",
		url: "https://api.github.com/users/IEmreOzkayaI",
		html_url: "https://github.com/IEmreOzkayaI",
		followers_url: "https://api.github.com/users/IEmreOzkayaI/followers",
		following_url: "https://api.github.com/users/IEmreOzkayaI/following{/other_user}",
		gists_url: "https://api.github.com/users/IEmreOzkayaI/gists{/gist_id}",
		starred_url: "https://api.github.com/users/IEmreOzkayaI/starred{/owner}{/repo}",
		subscriptions_url: "https://api.github.com/users/IEmreOzkayaI/subscriptions",
		organizations_url: "https://api.github.com/users/IEmreOzkayaI/orgs",
		repos_url: "https://api.github.com/users/IEmreOzkayaI/repos",
		events_url: "https://api.github.com/users/IEmreOzkayaI/events{/privacy}",
		received_events_url: "https://api.github.com/users/IEmreOzkayaI/received_events",
		type: "User",
		site_admin: false,
		name: "Emre",
		company: null,
		blog: "ozkayaemre.com",
		location: null,
		email: null,
		hireable: null,
		bio: null,
		twitter_username: null,
		public_repos: 41,
		public_gists: 0,
		followers: 8,
		following: 7,
		created_at: "2020-10-09T12:40:22Z",
		updated_at: "2023-12-09T16:15:59Z",
	},
};
